### ISSUE TITLE
Crash when loading JXL

### ISSUE THREAD

**Issue by RobbWatershed** [awxkee/jxl-coder-coil#7]
Tried to load multiple JXL files on an API29 device, using Coil 3.0.2 - I get a similar crash everytime :

```
A  Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7210d2c1f8 in tid 734 (DefaultDispatch), pid 32148
```

Some of the sample files I tried :
https://www.earth.org.uk/img/boiler/boiler-portrait-posterised-interlaced-256w.png.jxl
https://github.com/libjxl/conformance/raw/refs/heads/master/testcases/animation_icos4d/input.jxl
https://github.com/libjxl/conformance/raw/refs/heads/master/testcases/cafe/input.jxl

**Comment by awxkee** [comment]
Thanks for the info.
I can't actually reproduce this one, are you using emulator on x86 device? Or is it real android ARM device?

**Comment by RobbWatershed** [comment]
It's a physical ARM device (hisilicon kirin 710, to be perfectly precise).

My app uses Coil to load a couple other file formats without any problem. I just added `JxlDecoder.Factory()` at init time just like you wrote on the readme.

Gotta test on an x86 emu to see what happens...

**Comment by RobbWatershed** [comment]
It does the same thing on an emu hosted by a x86 PC.

**Comment by RobbWatershed** [comment]
If that's of any help, images aren't loaded from their URL but loaded from the device's storage. And yes, I'm certain of my credentials and URIs.

**Comment by RobbWatershed** [comment]
1/ I just found out that adding `.allowHardware(false)` to the Coil `ImageLoader` builder fixes the issue for still (non-animated) JXL images.

Is that mandatory to set `.allowHardware(false)`? If so , could you update your readme?


2/ I still get that same crash when trying to load animated JXLs.

**Comment by awxkee** [comment]
Could you, please, also confirm that behaviour are reproducible in the sample app here that I just commited or from CI [ImageToolbox](https://github.com/T8RIN/ImageToolbox/actions/runs/11828316497)

**Comment by awxkee** [comment]
> 1/ I just found out that adding `.allowHardware(false)` to the Coil `ImageLoader` builder fixes the issue for still (non-animated) JXL images.
> 
> Is that mandatory to set `.allowHardware(false)`? If so , could you update your readme?
> 
> 2/ I still get that same crash when trying to load animated JXLs.

Ah, ok. No `.allowHardware(false)` is not mandatory and should work.

Thanks for the info, I think I know what to check at least.

This is surprising since all [HarwareBuffers API](https://developer.android.com/ndk/reference/group/a-hardware-buffer#ahardwarebuffer_acquire) that I'm using should be available from 29 API, but on your device looks like it is not available.

**Comment by RobbWatershed** [comment]
> Could you, please, also confirm that behaviour are reproducible in the sample app here that I just commited or from CI [ImageToolbox](https://github.com/T8RIN/ImageToolbox/actions/runs/11828316497)

I installed `image-toolbox-3.1.0-rc01-foss-arm64-v8a-release-unsigned-signed.apk` on my device and tested Tools > JXL Tools > JXL to JPEG

I confirm that trying to load a still or an animated JXL does crash the app.

PS : I love what you've done for the UI ❤️

**Comment by awxkee** [comment]
Also, I'd like to ask run `adb shell cat /proc/cpuinfo` and paste here output

**Comment by RobbWatershed** [comment]
> Also, I'd like to ask run `adb shell cat /proc/cpuinfo` and paste here output

```
Processor       : AArch64 Processor rev 4 (aarch64)
processor       : 0
BogoMIPS        : 3.84
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 3.84
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
BogoMIPS        : 3.84
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
BogoMIPS        : 3.84
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 4
BogoMIPS        : 3.84
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 5
BogoMIPS        : 3.84
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 6
BogoMIPS        : 3.84
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 7
BogoMIPS        : 3.84
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

Hardware        : Hisilicon Kirin710
```

**Comment by awxkee** [comment]
Thanks! 
I think real issue is here, that **fphp** ( half precision float conversion ) cpu feature is missed. It is mandatory in android aarch64 specification so NDK always compiles everything like it is exists on CPU.
So I think issue here probably not a hardware buffer but _RGBA_F16_ type, even I can do checks in my code on **fphp** if it is exists and do software emulation if it is not, I cannot completely guarantee then that libjxl won’t hit missing instructions. 
Even in the very best case that I do all the checks, there are jxl images encoded in ‘half precision float’ as a storage type, and they cannot be ever opened on such devices, because libjxl actually compiled with meaning that **fphp** is available.

**Comment by awxkee** [comment]
And your crash is actually signaling that not existing CPU instructions is hit to be clear.

**Comment by RobbWatershed** [comment]
Oh yeah, ILL_ILLOPC = illegal operation I guess.

I just ran `adb shell cat /proc/cpuinfo` on the emu and **fphp** is also missing from flags.

If **fphp**  is mandatory in android aarch64, then why does Android Studio's emulator miss that instruction as well?

**Comment by awxkee** [comment]
> If **fphp** is mandatory in android aarch64, then why does Android Studio's emulator miss that instruction as well?

I don't know to be honest, **fphp** mandatory aarch64 part from 2017. Perhaps no one just worried about it, until AI time has come.
Android emulator just uses qemu, it is possible to launch with any features, and my emulator works with **fphp** ( what is also strange ).

Anyway, I think I'll do soon all the checks, and software emulation and this perhaps should help.

**Comment by RobbWatershed** [comment]
Thanks for taking the time to investigate this 😄

**Comment by awxkee** [comment]
Yep, thanks for information, this is always surprising to know that something that must exists do not exists. 
I’ll try to recompile libjxl with forcing disable on half floats availability but since is libhwy is under the hood I doubt in success, but I’ll let you know.

**Comment by awxkee** [comment]
Please, check 2.4.0.1 if it works

**Comment by awxkee** [comment]
I tried to disable fphp in libjxl, looks like it should work, however I'm not completely sure

**Comment by RobbWatershed** [comment]
Thanks for your responsiveness!

Unfortunately, 2.4.0.1 doesn't work. Plus activating `.allowHardware(false)` doesn't prevent crashes anymore.

**Comment by awxkee** [comment]
Sad, I don’t think that is issue is in hardware buffers, libjxl is about 150k lines of platform dependent multithreaded code in c++ and scaling library is about 100k lines hardware dependent Rust code, this is will be quite simple if just hardware buffers is an issuer here:)

I’ll do research what else may go wrong on non standard cpu, probably I’ll find it, however, I can’t promise that it will be fast.

One thing I may also try to ask you is try to force bitmap rgba8888 config and check if it changes something

**Comment by RobbWatershed** [comment]
Thank you. If I can be of any help by tracing or debugging something on my device, don't hesitate to send me pointers.

> One thing I may also try to ask you is try to force bitmap rgba8888 config and check if it changes something

Just did that - same crash (`Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x721bb3aa0c in tid 23587 (DefaultDispatch), pid 22530`)

**Comment by awxkee** [comment]
Maybe there is some stack trace or just SIGILL ?

**Comment by RobbWatershed** [comment]
Just SIGILL unfortunately. Probably because I'm using the release library... hence my suggestion.

**Comment by awxkee** [comment]
If you want to try debug this then download [jxl-coder itself](https://github.com/awxkee/jxl-coder) from master. Open Java_com_awxkee_jxlcoder_JxlCoder_decodeSampledImpl (JniDecoding.cpp) in C++ and just go step by step and somewhere it will fail,
This will be actually huge leap forward to understand what exactly happens.

**Comment by awxkee** [comment]
To make debugging a little convenient try do disable everything except arch you're actually targeting in gradle file by settings abiFilters = setOf("arm64-v8a")
```gradle
        externalNativeBuild {
            cmake {
                ndkVersion = "26.1.10909125"
                cppFlags.add ("-std=c++20")
                abiFilters += setOf("armeabi-v7a", "arm64-v8a", "x86_64", "x86")
            }
        }
```

**Comment by RobbWatershed** [comment]
Great! Let's see what I can find

**Comment by RobbWatershed** [comment]
I have a good and a bad piece of news.

Good one is I've managed to launch and debug **jxl-coder**.

Bad one is the crash is inside the Rust part, which Android studio can't debug.
Here's the call stack on the C++ side just before the crash (= about to call **weave_scale_u8**)
```
RescaleImage(std::__ndk1::vector<…> &, _JNIEnv *, unsigned int *, bool, unsigned int *, unsigned int *, unsigned int, unsigned int, unsigned int, bool, ScaleMode, XSampler, bool) SizeScaler.cpp:146
decodeSampledImageImpl(_JNIEnv *, std::__ndk1::vector<…> &, int, int, int, int, int, int) JniDecoding.cpp:123
Java_com_awxkee_jxlcoder_JxlCoder_decodeSampledImpl(JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint, jint) JniDecoding.cpp:313
```

Hope this helps~~

**Comment by awxkee** [comment]
Thanks a lot! Actually it is good news, at least clear where to search.
Did you try to use just decode without sampling? Does it work?

**Comment by awxkee** [comment]
Check, please, jxl-coder from latest master since you already have it. Hope this works

**Comment by RobbWatershed** [comment]
Sure. Right now I don't have access to my IDE but I'll get back on it later today.

**Comment by RobbWatershed** [comment]
Works like a charm!! 🥳  All images have been successfuly loaded and displayed ✅

Only problem I can see is the animated picture being not animated, but I guess doing that wasn't the point yet. Any way to test that too now that still images are OK?

**Comment by awxkee** [comment]
Good news!
You can check animated images by _JxlAnimatedImage_ class, see example how to make drawable [here](https://github.com/awxkee/jxl-coder-coil/blob/656349afb9554d3054f270339c4c5862972dd54c/jxlcodercoil/src/main/java/com/awxkee/jxlcoder/coil/AnimatedJxlDecoder.kt#L103C33-L103C49).

I’d like to notice that I did animated drawable with @T8RIN for demonstration purposes and it may be a little far away from real production use.

Making a really production ready rendering pipeline is a hard one, and far away from something I want to maintain 🫢 Especially with knowledge that decoding Jxl images still very slow, if compare to Avif(dav1d) at least x5-10 times, this makes writing any pipeline quite tricky since there is very slow decoding and no hardware acceleration.

if bugs are fixed, perhaps, tomorrow I’ll do release

**Comment by RobbWatershed** [comment]
> You can check animated images by JxlAnimatedImage class, see example how to make drawable here

Thanks. Can confirm it works too! We should be good to go~

**Comment by awxkee** [comment]
Try out 2.4.0.4 version, I think this should work perfectly

**Comment by RobbWatershed** [comment]
Err... it doesn't crash anymore, but there's still a problem somewhere 😅 

- With `.allowHardware(false)`, still images are displayed but animated images have only their 1st frame displayed

- With `.allowHardware(true)`, the output is garbage

NB1 : That's the very same device I've been testing with so far
NB2 : I can't see any suspicious trace in the logcat

![image](https://github.com/user-attachments/assets/5d9f04da-0946-410f-8d38-5a0c284aea11)
![image](https://github.com/user-attachments/assets/a4debeb4-e790-4918-bbe3-929cb93fc0e3)

**Comment by awxkee** [comment]
Are you using `AnimatedJxlDecoder` for animated images?

**Comment by RobbWatershed** [comment]
Yup, I loaded both Decoders during Coil init

**Comment by awxkee** [comment]
Both decoders wont work correctly :) At the moment there is a glitch in an animated factory after coil update, but you have to use only one. Animated factory is configured for still images.

**Comment by RobbWatershed** [comment]
My bad...

Now that `AnimatedJxlDecoder` has been set alone :
- `.allowHardware(false)` now animates animated images, but :
  - It's _much_ slower than what I saw yesterday using jxl-coder directly (maybe because hardware _is_ disabled?)
  - Animated pictures dimensions are stretched to the screen's dimensions (see screenshot below) instead of keeping an 1:1 ratio like still images do
 
![Screenshot_20241116_105721_me devsaki hentoid debug](https://github.com/user-attachments/assets/b8633e40-90c1-4b06-bcff-aac021c7fcb6)

- `.allowHardware(true)` still displays garbage output

**Comment by awxkee** [comment]
Does same behavior with hardware are reproducible on your device in jxl-coder directly ?
Yep, as I said animated rendering pipeline is a little far away from perfect, but this one I'll probably fix.
It's slower and the moment perhaps by upscaling images to screen size.

For a hardware buffers more hard to say what there goes on, there is no any specific conversion, hardware dependend code for this, there is just copying data to HB, and I'm not recognizing this error pattern in the image, it more looks like to me that HB just filled with random alloc data then it means that data is not copied or copied somewhere in unknown place. I do all the checks on successful acquiring HB copying and others, so at least it all signals about **success**.

Could you please check that in `ReformatBitmap.cpp` lane 277 
```c++
AHardwareBuffer_describe_compat(hardwareBuffer, &bufferDesc);
```
After call to this method `bufferDesc` is filled with correct data ( width, height etc )?

**Comment by awxkee** [comment]
You may not check, I'm filling this. So actually about HB I have no idea at the moment what to check.

**Comment by awxkee** [comment]
Do you have in your app any custom decoder that completely custom filling hardware buffers by itself using dynamic linking?
When I did this I not found any library doing so, on so, ly mobile Firefox do so.

**Comment by RobbWatershed** [comment]
> Does same behavior with hardware are reproducible on your device in jxl-coder directly ?

I'm gonna check that, plus using Coil instead of Compose to display the pic on the jxl-coder app.

> Do you have in your app any custom decoder that completely custom filling hardware buffers by itself using dynamic linking?

I'm not sure how to check that. For image processing, I'm using :
- Coil3
- APNG4Android (through a Coil Decoder)
- A custom [OpenGL-powered rendering module](https://github.com/avluis/Hentoid/tree/master/app/gles-renderer/src/main/java/me/devsaki/hentoid/gles_renderer) to resize images on the fly using GPU rather than CPU

But none of them are used at the same time or in a pipeline. They're activated separately depending of the type of image to be processed (native Android support or not, animated or not...)

**Comment by awxkee** [comment]
> I'm not sure how to check that. For image processing, I'm using :
> 
>     * Coil3
> 
>     * APNG4Android (through a Coil Decoder)
> 
>     * A custom [OpenGL-powered rendering module](https://github.com/avluis/Hentoid/tree/master/app/gles-renderer/src/main/java/me/devsaki/hentoid/gles_renderer) to resize images on the fly using GPU rather than CPU
> 
> 
> But none of them are used at the same time or in a pipeline. They're activated separately depending of the type of image to be processed (native Android support or not, animated or not...)

Yup, but none of them actually operates on Hardware Buffers directly.

If it is possible it will be interesting to check if [libpag](https://github.com/Tencent/libpag) works on your device, they are using same approach as I do. If their code works at least I can copy their flags because everything else looks same to me.

> * A custom [OpenGL-powered rendering module](https://github.com/avluis/Hentoid/tree/master/app/gles-renderer/src/main/java/me/devsaki/hentoid/gles_renderer) to resize images on the fly using GPU rather than CPU

Little offtop:
Actually for still images using OpenGL/Vulkan is quite ineffective, even if not consider that GPUImage is not correctly designed and quite slow by design and most of processing algorithms there simply incorrect.

**Comment by awxkee** [comment]
Actually I already changed in jxl-coder flags to be the same as in libpag

**Comment by RobbWatershed** [comment]
So far I can't fathom what's going on. I can correctly display any JXL picture on the jxl-coder app, using HARDWARE bitmapConfig, but when I do the same with my app, it comes out garbled.

I'll continue to experiment and keep you informed.

>Little offtop:
>Actually for still images using OpenGL/Vulkan is quite ineffective, even if not consider that GPUImage is not correctly designed and quite slow by design and most of processing algorithms there simply incorrect.

I'm far from being specialized in the arcane of image processing and simply thought it would be better to leverage the GPU instead of doing everything on CPU. Plus my previous implementation was on RenderScript, and [Google recommended to switch to Vulkan](https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html).

After [testing a few alternatives](https://github.com/RobbWatershed/renderscript-alternatives-benchmark), I opted for OpenGL for compatibility's sake, and because GLES doesn't require to write C/C++ code. As you saw, the code is heavily inspired by [GPUImage](https://github.com/cats-oss/android-gpuimage) but I'm unable to optimize it as I'm not familiar with that domain.

Do you think scaling with [aire](https://github.com/awxkee/aire) would perform better?

**Comment by awxkee** [comment]
> So far I can't fathom what's going on. I can correctly display any JXL picture on the jxl-coder app, using HARDWARE bitmapConfig, but when I do the same with my app, it comes out garbled.
> 
> I'll continue to experiment and keep you informed.

Might be coil, if you using it, is doing something wrong? If there is an processing somewhere for example, _HARDWARE_ bitmaps must be handled differently. Your images looks like something tried to copy data from it ( or into it ?), but it is not allowed in android and there is just a hole.





> I'm far from being specialized in the arcane of image processing and simply thought it would be better to leverage the GPU instead of doing everything on CPU. Plus my previous implementation was on RenderScript, and [Google recommended to switch to Vulkan](https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html).
> 
> After [testing a few alternatives](https://github.com/RobbWatershed/renderscript-alternatives-benchmark), I opted for OpenGL for compatibility's sake, and because GLES doesn't require to write C/C++ code. As you saw, the code is heavily inspired by [GPUImage](https://github.com/cats-oss/android-gpuimage) but I'm unable to optimize it as I'm not familiar with that domain.
> 
> Do you think scaling with [aire](https://github.com/awxkee/aire) would perform better?

[Here](https://developer.android.com/guide/topics/renderscript/migrate) is migration article they clearly stating that in many cases C/C++ solutions is better.

At the moment, writing Vulkan in android app is something horrible, I can't recommend that. While it is in its current state it is not possible to write Vulkan code more performant than OpenGL in android, if you're not highly skilled in GPU processing.

In common, GPU processing worth it only when you're able to write contiguous Rendering pipeline without transferring textures from RAM to GPU on each operation ( and this is exactly what GPUImage is doing ), if you're not able doing so, transferring time in common will be longer than straightforward C++ code, and there are Command Buffer submitting time, shader execution time and other things.
Yup, I'd expect aire to be at least twice as fast in process still images rather than GPUImage for common cases. At least you can try it on since you're already have a sample app.

**Comment by RobbWatershed** [comment]
> Might be coil, if you using it, is doing something wrong? If there is an processing somewhere for example, HARDWARE bitmaps must be handled differently. Your images looks like something tried to copy data from it ( or into it ?), but it is not allowed in android and there is just a hole.

Looks like the problem is caused by `ImageView` dimensions being dynamic (`LayoutParams.MATCH_PARENT`). Loading succeeds when dimensions are fixed using an absolute value, but fails when they change dynamically. Hardware bitmap must be somehow adjusted when that happens, which causes issues. And I can't circumvent that as my views must be resized dynamically.

=> Consider the issue solved (no crash anymore 🎉). I'm switching to `Bitmap.Config.ARGB_8888` for the time being. 
Thanks a lot for your patience!

> Yup, I'd expect aire to be at least twice as fast in process still images rather than GPUImage for common cases. At least you can try it on since you're already have a sample app.

Sounds promising. I'll let you know soon 😉

**Comment by awxkee** [comment]
> Sounds promising. I'll let you know soon 😉

This will interesting to know! Specifically on device with your CPU

**Comment by RobbWatershed** [comment]
Going off-topic for good (but the issue's closed, so...)

I've integrated aire to [my benchmark app](https://github.com/RobbWatershed/renderscript-alternatives-benchmark).

What I measured so far :
- Vulkan is still performing best by far, but as you said, it's much more complex to integrate and maintain (plus you can't be sure Vulkan is available on a given device until API29)
- **Blur (Gaussian)** : aire is performing better than OpenGL
- **Resize (Lanczos3)** : aire is performing
  - Slower than OpenGL when downscaling (and way slower when downscaling much)
  - Faster than OpenGL when upscaling (and way faster when upscaling much)

Depending on the original image resolution, device resolution and user zoom level, my app may perform as much downscaling as upscaling.

=> Not certain I have a full case for migrating to aire yet, but I'll definitely consider it if I have to add extra transformations.

**Comment by awxkee** [comment]
> Going off-topic for good (but the issue's closed, so...)

No worries :)

Thanks for trying!

You're using LINEAR colorspace for downscaling ( what is correct for sure but require do additional processing and will work in full precision ), to make a comparable checks you have to set ColorSpace = SRGB because your shader code always assume SRGB.

It is not possible to check downscaling for Lancos3 properly with your implementation because for downscaling your implementation is, highly likely, do just affine transformation without antialias, what is incorrect. You can try out `Spline36`, it have a little bigger kernel (15%) but this kernel should not do antialiasing.

Here is downsampled image 8 times to understand what antialias does. Downscaled image without antialias almost always same as Nearest what is already cheap enough.

![converted](https://github.com/user-attachments/assets/34d92426-e688-4188-92d8-8f4ead1b8f57)
![converted_noantialias](https://github.com/user-attachments/assets/9da8a74c-056a-46c8-8cc7-f0c35c0285bb)

Your code has fixed [6 taps of lanczos3](https://github.com/RobbWatershed/renderscript-alternatives-benchmark/blob/2fe0ff8493b2cc980595e3b5a0b0aa6ac7ced996/app/src/main/java/com/android/example/rsmigration/filter/GPUImageResizeFilter.java#L87) so it is not really correct for upscaling or scaling to close size ( because it should have 3 taps), but it is exact amount of taps for effectively halving image size with antialias, any other size it is more correct to consider invalid. Actually, shader code looks a little suspicious, might be more errors there, and I'm quite sure they are there, but from skimming it looks so.

Here is how linearization changes results ( brigther is correct one where it is linearized ), open in different windows to see the difference. Those images are from blurring but for rescaling effect the same: dark tones moves towards zero, bright tones completely killed and mid tones slightly shiftes down.

![378164273-d4e21bd3-62c8-448b-9358-38bf28a44494](https://github.com/user-attachments/assets/8d399026-3fb4-49fc-a0ed-944f3a90a217)
![378164271-4284b6a6-5217-4586-8600-863e3991297a](https://github.com/user-attachments/assets/847e82e1-9b70-4ebe-bdae-4486568815ee)



> => Not certain I have a full case for migrating to aire yet, but I'll definitely consider it if I have to add extra transformations.

I wouldn't actually recommend because it already have tons of code that you probably will never need, and as it have a lot of native code it is quite greedy to size in android app. But at least you can try out to improve your implementations if you want to.

P.S. `stackBlur` is the fastest option in Aire and `gaussianBlur` if for some reason you want pure gaussian.

**Comment by awxkee** [comment]
As I mentioned before, actual issue of GPUImage incorrect design, and most of algorithms are incorrect.
Vulkan is hard to compare because it require a lot of manual untrivial code.

Vulkan shaders are correct, blur is fully correct ( without linearization but it is actually optional just for level of effect correctness and image distortion ), resize shader is essentially affine transformation with always fixed taps, so for downscaling it will always very fast and do as nearest interpolation, except lanczos that have some _magic_ coefficients and from the first sight hard to understand what are they actually are.

**Comment by awxkee** [comment]
Also here is short note that if you do parallel image processing in your app Vulkan available instances is limited, as long as OpenGL instances and their performance penalties is grows sharply, so it's better to not allow more than a few simultaneously processing images, or use same command buffer instead for fast sequence processing, as you can start encode next command without waiting until previous is finished.

**Comment by awxkee** [comment]
I was curious to try out how at least correct OpenGL implementation will be and this is actually fast enough.
Here is the [gist](https://gist.github.com/awxkee/20e3863be06507ba53285e343597bf27) there is GLES2 and GLES3 implementation, actually GLES2 even faster on my device that computing shaders.
It is exactly 2 times slower than Vulkan, and 2 times faster ( and correct ) than GPUImage.
It performs pure gaussian blur.

Class is thread bound so you cannot call if from different threads and to have full advantage of render pass and reuse buffers you should cache it and reuse

```kotlin
    override fun blur(radius: Float, outputIndex: Int): Bitmap {
        if (blurRenderPass == null) {
            blurRenderPass = OpenGLESBlurRenderPass(context)
        }
        return blurRenderPass!!.render(input, radius.toInt())
    }
```

**Comment by awxkee** [comment]
> I was curious to try out how at least correct OpenGL implementation will be and this is actually fast enough. Here is the [gist](https://gist.github.com/awxkee/20e3863be06507ba53285e343597bf27) there is GLES2 and GLES3 implementation, actually GLES2 even faster on my device than GL3 computing shaders. It is exactly 2 times slower than Vulkan, and 2 times faster ( and correct ) than GPUImage. It performs pure gaussian blur.
> 
> Class is thread bound so you cannot call if from different threads and to have full advantage of render pass and reuse buffers you should cache it and reuse
> 
> ```kotlin
>     override fun blur(radius: Float, outputIndex: Int): Bitmap {
>         if (blurRenderPass == null) {
>             blurRenderPass = OpenGLESBlurRenderPass(context)
>         }
>         return blurRenderPass!!.render(input, radius.toInt())
>     }
> ```

This is might be not fully correct implementation

**Comment by awxkee** [comment]
I was curious to try out how at least correct OpenGL implementation will be and this is actually fast enough. Here is the [gist](https://gist.github.com/awxkee/20e3863be06507ba53285e343597bf27) there is GLES2 and GLES3 implementation, actually GLES2 even faster on my device than GL3 computing shaders. It is exactly 2 times slower than Vulkan, and 2 times faster ( and correct ) than GPUImage. It performs pure gaussian blur.
Class is thread bound so you cannot call if from different threads and to have full advantage of render pass and reuse buffers you should cache it and reuse
```kotlin
     override fun blur(radius: Float, outputIndex: Int): Bitmap {
        if (blurRenderPass == null) {
             blurRenderPass = OpenGLESBlurRenderPass(context)
      }
        return blurRenderPass!!.render(input, radius.toInt())
     }
```
